config/routes.rb
Rails.application.routes.draw do
  resources :shots do
    resources :comments
    member do
      put 'like', to: "shots#like"
      put 'unlike', to: "shots#unlike"
    end
  end
  devise_for :users , controllers: {registrations: 'registrations'}
  root 'shots#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/my_shots" , to: "shots#my_shots" , as: "my_shots"
  resources :profile
  get "/all_users" , to: "home#all_users" , as: "all_users"
  get "/follow_request" , to: "home#follow_request" , as: "follow_request"
  get "/current_profile" , to: "home#current_profile" , as: "current_profile"

  post "/profile/:id/follow" , to: "profile#follow" , as: "follow"
  post "/profile/:id/unfollow" , to: "profile#unfollow" , as: "unfollow"
  post "/profile/:id/accept" , to: "profile#accept" , as: "accept"
  post "/profile/:id/decline" , to: "profile#decline" , as: "decline"
  post "/profile/:id/cancel" , to: "profile#cancel" , as: "cancel"
  get '/message' , to: "profile#message" ,as: "message"

  resources :conversations do
    resources :messages
  end
end

app/models/shot.rb
class Shot < ApplicationRecord

    belongs_to :user
    has_one_attached :image
    has_many :comments , dependent: :destroy
    is_impressionable
    acts_as_votable
end

app/controllers/shots_controller.rb
class ShotsController < ApplicationController
  before_action :authenticate_user! , except: [:index , :show , :like , :unlike]
  before_action :set_shot, only: %i[show edit update destroy like unlike]
  impressionist actions: [:show], unique: [:impressionable_type, :impressionable_id, :user_id]
  before_action :validate_owner, only: %i[edit update destroy]

  # GET /shots or /shots.json
  def index
    @shots = Shot.all.order("created_at DESC")
  end

  # GET /shots/1 or /shots/1.json
  def show
  end

  # GET /shots/new
  def new
    @shot = current_user.shots.build
  end
  
  # GET /shots/1/edit
  def edit
  end
  
  # POST /shots or /shots.json
  def create
    @shot = current_user.shots.build(shot_params)
    @shot.user_id = current_user.id
    
    if @shot.save
      redirect_to shot_url(@shot), notice: "Shot was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  # PATCH/PUT /shots/1 or /shots/1.json
  def update
    if @shot.update(shot_params)
      redirect_to shot_url(@shot), notice: "Shot was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /shots/1 or /shots/1.json
  def destroy
    @shot.destroy
    redirect_to shots_url, notice: "Shot was successfully destroyed."
  end

  def my_shots
    if user_signed_in?
      @shots = current_user.shots.all
      @shot = Shot.new
    end
  end

  def like
    @shot.liked_by current_user
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.js {render layout:false}
    end
  end
  
  def unlike
    @shot.unliked_by current_user
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.js {render layout:false}
    end
  end
  private

  def validate_owner
    if @shot.user_id != current_user.id
      return redirect_to root_path, notice: 'You are not authorized to manipulate this shot'
    end
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_shot
    @shot = Shot.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def shot_params
    params.require(:shot).permit(:title, :description, :user_id, :image)
  end
end

app/helpers/shots_helper.rb
module ShotsHelper
end

app/views/shots/_form.html.erb
<%= form_with(model: shot) do |form| %>
  <% if shot.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(shot.errors.count, "error") %> prohibited this shot from being saved:</h2>
      <ul>
        <% shot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <div class="image-container" style="margin : 1rem 0;width : 100%;">
      <label for="input" style="width : 100%;height : 23rem;">
        <span class="label_for_box_input ">
        UPLOAD 
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-upload" viewBox="0 0 16 16">
          <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
          <path d="M7.646 1.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1-.708.708L8.5 2.707V11.5a.5.5 0 0 1-1 0V2.707L5.354 4.854a.5.5 0 1 1-.708-.708l3-3z"/>
        </svg>
        </span>
          <img id="image-preview" src="img.png" class="image-preview lable_dialouge_box_for_input"/>
      </label>
    </div>
    <%= form.file_field :image, id: "input", accept: "image/*", class: "hide_input", onchange: "updateImagePreview()" %>

  </div>
 <div class="form-floating" style="margin : 1rem 0;">
    <%= form.text_field :title , required: :true , class: "form-control" ,id:"floatingTextarea2"%>
    <%= form.label :title, style: "display: block" ,id:"floatingTextarea2"%>
  </div>

  <div class="form-floating" style="margin : 1rem 0;">
    <%= form.text_area :description, required: :true, style:"height: 200px" , class: "form-control" ,id:"floatingTextarea2"%>
    <%= form.label :description, style: "display: block" ,id:"floatingTextarea2"%>
  </div>

  <div style="text-align : center; display : flex; align-items : center; justify-content : center; ">
    <%= form.submit class: "btn btn-success"%>
    <%= link_to "Back to shots", shots_path  , style: "margin-left : 1rem;" , class: "btn btn-secondary"%>
  </div>
<%end%>


<script>
  const imagePreview = document.getElementById("image-preview");
  const input = document.getElementById("input");

  function updateImagePreview() {
    const selectedFile = input.files[0];

    if (selectedFile) {
      const objectURL = URL.createObjectURL(selectedFile);
      imagePreview.src = objectURL;
    } else {
      imagePreview.src = "img.png"; // Default image when no file is selected
    }
  }

  // You can also call the function initially to handle any default value
  updateImagePreview();
</script>

app/views/shots/_likeunlike.html.erb
<h2>Like this Post</h2>
<%if user_signed_in?%>
    <% if current_user.liked? shot %>
    <%= link_to unlike_shot_path(shot) , data: {turbo_method: :put} , class: "unlike_shot btn btn-primary d-flex justify-content-center align-items-center" , style: "text-decoration :none; color : white; font-size : 1.3rem;" do %>
        UnLike <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" style="margin-left :.6rem;" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                    <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                </svg>
    <% end %>
    <%else%>
    <%= link_to like_shot_path(shot) , data: {turbo_method: :put} , class: "like_shot btn btn-primary d-flex justify-content-center align-items-center" , style: "text-decoration :none; color : white; font-size : 1.3rem;" do %>
        Like <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" style="margin-left :.6rem;" fill="currentColor" class="bi bi-hand-thumbs-up" viewBox="0 0 16 16">
                <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.144 2.144 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a9.84 9.84 0 0 0-.443.05 9.365 9.365 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111L8.864.046zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a8.908 8.908 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.224 2.224 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.866.866 0 0 1-.121.416c-.165.288-.503.56-1.066.56z"/>
            </svg>
    <% end %>
    <% end %>
<%else%>
    <%= link_to new_user_session_path, class: "like_shot btn btn-primary d-flex justify-content-center align-items-center" , style: "text-decoration :none; color : white; font-size : 1.3rem;" do %>
        Like <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" style="margin-left :.6rem;" fill="currentColor" class="bi bi-hand-thumbs-up" viewBox="0 0 16 16">
                <path d="M8.864.046C7.908-.193 7.02.53 6.956 1.466c-.072 1.051-.23 2.016-.428 2.59-.125.36-.479 1.013-1.04 1.639-.557.623-1.282 1.178-2.131 1.41C2.685 7.288 2 7.87 2 8.72v4.001c0 .845.682 1.464 1.448 1.545 1.07.114 1.564.415 2.068.723l.048.03c.272.165.578.348.97.484.397.136.861.217 1.466.217h3.5c.937 0 1.599-.477 1.934-1.064a1.86 1.86 0 0 0 .254-.912c0-.152-.023-.312-.077-.464.201-.263.38-.578.488-.901.11-.33.172-.762.004-1.149.069-.13.12-.269.159-.403.077-.27.113-.568.113-.857 0-.288-.036-.585-.113-.856a2.144 2.144 0 0 0-.138-.362 1.9 1.9 0 0 0 .234-1.734c-.206-.592-.682-1.1-1.2-1.272-.847-.282-1.803-.276-2.516-.211a9.84 9.84 0 0 0-.443.05 9.365 9.365 0 0 0-.062-4.509A1.38 1.38 0 0 0 9.125.111L8.864.046zM11.5 14.721H8c-.51 0-.863-.069-1.14-.164-.281-.097-.506-.228-.776-.393l-.04-.024c-.555-.339-1.198-.731-2.49-.868-.333-.036-.554-.29-.554-.55V8.72c0-.254.226-.543.62-.65 1.095-.3 1.977-.996 2.614-1.708.635-.71 1.064-1.475 1.238-1.978.243-.7.407-1.768.482-2.85.025-.362.36-.594.667-.518l.262.066c.16.04.258.143.288.255a8.34 8.34 0 0 1-.145 4.725.5.5 0 0 0 .595.644l.003-.001.014-.003.058-.014a8.908 8.908 0 0 1 1.036-.157c.663-.06 1.457-.054 2.11.164.175.058.45.3.57.65.107.308.087.67-.266 1.022l-.353.353.353.354c.043.043.105.141.154.315.048.167.075.37.075.581 0 .212-.027.414-.075.582-.05.174-.111.272-.154.315l-.353.353.353.354c.047.047.109.177.005.488a2.224 2.224 0 0 1-.505.805l-.353.353.353.354c.006.005.041.05.041.17a.866.866 0 0 1-.121.416c-.165.288-.503.56-1.066.56z"/>
            </svg>
    <% end %>
<%end%>

app/views/shots/_shot.html.erb
<div>
  <div id="<%= dom_id(shot) %>" class="single_shot_div">
    <div class="upper_image_div">
      <div class="image_show_div">
        <%= link_to shot do %>
          <% if shot.image.attached? %>
            <%= image_tag(shot.image, height: "100%;", class: "shot-image") %>
          <% end %>
        <% end %>
        <div class="info_div info-hidden">
          <div class="title_for_shot">
            <%= shot.title %>
          </div>
          <div class="desc_for_shot">
            <%= simple_format(shot.description) %>
          </div>
        </div>
      </div>
    </div>
    <div class="show_time_of_post">
      Created <%= time_ago_in_words(shot.created_at) %> ago
    </div>
    <div class="icons_div_single_post">
      <div class="watch_icon">
        <%= link_to shot do %>
          <%= shot.impressionist_count%> <i class="fa fa-eye"></i>
        <% end %>
      </div>
      <div class="watch_icon">
        <%= link_to shot do %>
          <%= shot.comments.count%> <i class="fa fa-comment"></i>
        <% end %>
      </div>
      <div class="watch_icon">
        <%if user_signed_in?%>
          <% if current_user.liked? shot %>
            <%= link_to unlike_shot_path(shot) , data: {turbo_method: :put} , class: "unlike_shot" do %>
              <%= shot.get_likes.size%> <i class="fa fa-heart text-danger"></i>
            <% end %>
          <%else%>
            <%= link_to like_shot_path(shot) , data: {turbo_method: :put} , class: "like_shot" do %>
              <%= shot.get_likes.size%> <i class="fa fa-heart"></i>
            <% end %> 
          <% end %>
        <%else%>
          <%= link_to like_shot_path(shot) , data: {turbo_method: :put} , class: "like_shot" do %>
            <%= shot.get_likes.size%> <i class="fa fa-heart"></i>
          <% end %>
        <%end%>
      </div>
    </div>
  </div>
  <div class="user_info_div_single_post">
    <div class="image_of_post_user">
      <%= image_tag(shot.user.image, height: "35rem", width: "35rem", style: "border-radius: 50%;") %>
    </div>
    <div class="name_post_user_div">
      <%= shot.user.name%>
    </div>
  </div>
</div>

app/views/shots/edit.html.erb
<div class="new_create_div_dribble">

  <h1>Edit a shot</h1>

  <div class="inner_form_div for_edit_additional_class">
    <%= render "form", shot: @shot %>
  </div>

</div>

app/views/shots/index.html.erb
<div class="all_shots_div">
  <% @shots.each do |shot| %>
    <%= render shot %>
  <% end %>
</div>

app/views/shots/my_shots.html.erb
<div class="all_shots_div">
  <% @shots.each do |shot| %>
    <div>
        <div class="single_shot_div">
        <div class="upper_image_div">
            <div class="image_show_div">
            <%= link_to shot do %>
                <% if shot.image.attached? %>
                <%= image_tag(shot.image, height: "100%", class: "shot-image") %>
                <% end %>
            <% end %>
            <div class="info_div info-hidden">
                <div class="title_for_shot">
                <%= shot.title %>
                </div>
                <div class="desc_for_shot">
                <%= shot.description %>
                </div>
            </div>
            </div>
        </div>
        <div class="show_time_of_post">
            Created <%= time_ago_in_words(shot.created_at) %> ago
        </div>

    <div class="icons_div_single_post">
      <div class="watch_icon">
        <%= link_to shot do %>
          <%= shot.impressionist_count%> <i class="fa fa-eye"></i>
        <% end %>
      </div>
      <div class="watch_icon">
        <%= link_to shot do %>
          <%= shot.comments.count%> <i class="fa fa-comment"></i>
        <% end %>
      </div>
      <div class="watch_icon">
        <%if user_signed_in?%>
          <% if current_user.liked? shot %>
            <%= link_to unlike_shot_path(shot) , data: {turbo_method: :put} , class: "unlike_shot" do %>
              <%= shot.get_likes.size%> <i class="fa fa-heart text-danger"></i>
            <% end %>
          <%else%>
            <%= link_to like_shot_path(shot) , data: {turbo_method: :put} , class: "like_shot" do %>
              <%= shot.get_likes.size%> <i class="fa fa-heart"></i>
            <% end %> 
          <% end %>
        <%else%>
          <%= link_to like_shot_path(shot) , data: {turbo_method: :put} , class: "like_shot" do %>
            <%= shot.get_likes.size%> <i class="fa fa-heart"></i>
          <% end %>
        <%end%>
      </div>
    </div>
        </div>
        <div class="user_info_div_single_post">
        <div class="image_of_post_user">
            <%= image_tag(shot.user.image, height: "35rem", width: "35rem", style: "border-radius: 50%") %>
        </div>
        <div class="name_post_user_div">
            <%= shot.user.name %>
        </div>
        </div>
    </div>
  <% end %>
  <%= link_to new_shot_path , style: "text-decoration : none;" , onclick: "setTimeout(function() { location.reload(); }, 1000);" do %>
    <div class="add_a_post_div single_shot_div">
        <div class="plus_icon_for_new">
            <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-plus-square-fill" viewBox="0 0 16 16">
                <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.5 4.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3a.5.5 0 0 1 1 0z"/>
            </svg>
        </div>
        <div class="add_message_for_the_new">
            Add a new Shot
        </div>
    </div>
  <% end %>
</div>

app/views/shots/new.html.erb
<div class="new_create_div_dribble">

  <h1>Create a New Shot !</h1>

  <div class="inner_form_div for_edit_additional_class">
    <%= render "form", shot: @shot %>
  </div>
  <br>

</div>

app/views/shots/show.html.erb
<div class="outer_main_div_for_shots_show">

  <div class="show_main_div">
    <div class="title_for_shot_show_page">
      <%= @shot.title %>
    </div>
    <div class="time_stamp_for_show">
      <div class="time_stamp_for_show">
        <div class="post_info_div">
          Created by <span class="post_user_show_name"><%= @shot.user.name%></span>
        </div>
        <div class="time_for_show">
          on <span style= "color: black; font-weight: bold"><%= verbose_date(@shot.created_at) %></span>
        </div>
      </div>
      <% if user_signed_in? && @shot.user_id === current_user.id %>
        <div class="lower_btn_div_for_show_post">
          <%= link_to "Back to shots", shots_path , class: "btn btn-secondary"%>
          <%= link_to "Edit ", edit_shot_path(@shot), onclick: "setTimeout(function() { location.reload(); }, 1000);" , class: "btn btn-primary" %>
          <%= link_to "Delete", @shot, data: { turbo_method: :delete , turbo_confirm: "Are you sure to Delete" }, class: "btn btn-danger" %>
        </div>
      <% end %>
    </div>
    <% if @shot.image.present? %>
      <div class="upper_image_div_for_shot">
        <%= image_tag(@shot.image, height: "300rem") %>
      </div>
    <% end %>
    <div class="description_for_shot_show_page">
      <%= simple_format(@shot.description) %>
    </div>
    <div class="comments_section_main_div">
      <div class="total_comments_div_on_top">
        <%= pluralize(@shot.comments.count , "Comment")%>
      </div>
      <div class="render_comments_on_show_page">
        <%= render @shot.comments%>
      </div>
      <div class="form_for_comments_div">
        <% if user_signed_in?%>
          <h2>
            Leave a Reply
          </h2>
          <%= render 'comments/form' %>
        <%else%>
          <div style="color : black; ">
            <%= link_to "Sign in" , new_user_session_path , style: "#E600A1"%> to leave a Comment
          </div>
        <%end%>
      </div>
    </div>
  </div>

  <div class="pannel_for_counts_of_actions">
    <div class="inner_pannel_div_for_action">
    <div class="like_div_for_post">
      <%= render 'likeunlike' ,shot: @shot %>
    </div>
      <ul class="list-group">
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div><i class="fa fa-heart" style="margin-right : .7rem;"></i>Likes</div>
          <span class="badge rounded-pill" style="background: #E600A1;"><%= @shot.get_likes.size %></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div><i class="fa fa-comment" style="margin-right : .7rem;"></i>Comments</div>
          <span class="badge rounded-pill" style="background: #E600A1;"><%= @shot.comments.count%></span>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div><i class="fa fa-eye" style="margin-right : .7rem;"></i>Views</div>
          <span class="badge rounded-pill" style="background: #E600A1;"><%= @shot.impressionist_count%></span>
        </li>
      </ul>
    </div>
  </div>

</div>