config/routes.rb
Rails.application.routes.draw do
  resources :shots do
    resources :comments
    member do
      put 'like', to: "shots#like"
      put 'unlike', to: "shots#unlike"
    end
  end
  devise_for :users , controllers: {registrations: 'registrations'}
  root 'shots#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "/my_shots" , to: "shots#my_shots" , as: "my_shots"
  resources :profile
  get "/all_users" , to: "home#all_users" , as: "all_users"
  get "/follow_request" , to: "home#follow_request" , as: "follow_request"
  get "/current_profile" , to: "home#current_profile" , as: "current_profile"

  post "/profile/:id/follow" , to: "profile#follow" , as: "follow"
  post "/profile/:id/unfollow" , to: "profile#unfollow" , as: "unfollow"
  post "/profile/:id/accept" , to: "profile#accept" , as: "accept"
  post "/profile/:id/decline" , to: "profile#decline" , as: "decline"
  post "/profile/:id/cancel" , to: "profile#cancel" , as: "cancel"
  get '/message' , to: "profile#message" ,as: "message"

  resources :conversations do
    resources :messages
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_user!
  def all_users
    @users = User.all
  end

  def follow_request
    
  end

  def current_profile

  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <%= link_to 'Dribble', root_path, class: 'navbar-brand', style: 'color: #DB4F8E; font-weight: bold;' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <button class="btn btn-secondary">
              <%= image_tag(current_user.image, height: '30rem', width: '30rem', style: 'object-fit: cover; border-radius: 50%;') %>
              <%= current_user.name %>
          </button>
        <%end%>
          <%= link_to 'Create a Shot', new_shot_path, class: 'nav-link active', 'aria-current' => 'page', onclick: "setTimeout(function() { location.reload(); }, 1000);"  %>
        <li class="nav-item">
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'My Shots', my_shots_path, class: 'nav-link active', class:"nav-link"%>
          </li>
          <li class="nav-item">
            <%= link_to 'Conversations', conversations_path, class: 'nav-link active', class:"nav-link"%>
          </li>
        <%end%>
      </ul>
      <div>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="display : flex ; align-items : center">
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to follow_request_path, class: 'nav-link active btn btn-dark position-relative' do %>
              <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-bell-fill" viewBox="0 0 16 16">
                <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zm.995-14.901a1 1 0 1 0-1.99 0A5.002 5.002 0 0 0 3 6c0 1.098-.5 6-2 7h14c-1.5-1-2-5.902-2-7 0-2.42-1.72-4.44-4.005-4.901z"/>
              </svg>
                <% if  current_user.follow_requests.count > 0 %>
                  <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
                    <%= current_user.follow_requests.count%>
                  </span>
                <% end %>
            <% end %>
          </li>
          <li class="nav-item">
              <%= link_to 'Add Friends', all_users_path, class: 'nav-link active', 'aria-current' => 'page'%>
            </li>
            <li class="nav-item">
              <%= link_to "Edit Profile", edit_user_registration_path , class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to "View Profile", current_profile_path , class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%= link_to 'Log Out', destroy_user_session_path, data: {turbo_method: :delete}, class: 'nav-link' %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Login', new_user_session_path, class: 'nav-link' %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/home/all_users.html.erb
<div class="outer_all_user_div">
    <div class="messsage_on_the_top_of_users">
        Wanna follow some Users?
    </div>
    <% @users.each do |user| %>
        <% next if user == current_user %>
        <div class="single_user_inner_div_all_users">
            <div class="left_side_picture_of_single_user">
                <%= image_tag(user.image, height: "50rem", width: "50rem", style: "border-radius: 50%;") %>
            </div>
            <div class="right_side_info_of_single_user_all_users">
                <div class="upper_name_of_user_all_users">
                    <%= link_to user.name, profile_path(user) %>
                </div>
                <div class="lower_email_of_user_all_users">
                    <%= user.email %>
                </div>
                <% if current_user.following?(user) %>
                    <%= button_to "Unfollow", unfollow_path(user), class: "btn btn-outline-primary", style: "margin-top: .6rem;" %>
                <% elsif current_user.sent_follow_request_to?(user) %>
                    <%= button_to "Cancel Request", cancel_path(user), class: "btn btn-danger", style: "margin-top: .6rem;" %>
                <% else %>
                    <%= button_to "Follow", follow_path(user), class: "btn btn-primary", style: "margin-top: .6rem;" %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

app/views/home/current_profile.html.erb
<div class="current_user_outer_div_profile">
    <div class="inner_div_for_current_user_profile">
        <div class="left_side_profile_info_div_curret_user">
            <div class="upper_left_current_image_div">
                <%= image_tag(current_user.image, style: 'object-fit: cover; border-radius: 50%; height: 18rem; width: 18rem;') %>
            </div>
            <div class="lower_profile_left_current_user_div">
                <div class="name_of_user_upper_part">
                    <%= current_user.name%>
                </div>
                <div class="email_of_user_upper_part">
                    <%= current_user.email%>
                </div>
                <div class="follwoing_and_followers_count_div">
                    <div class="following_uppper_profile_div">
                        <span><%= current_user.following.count%></span> Follwoing
                    </div>
                    <div class="followers_uppper_profile_div">
                        <span><%= current_user.followers.count%></span> Followers
                    </div>
                </div>
                <div class="following_uppper_profile_div">
                    <span style="font-size : 1.3rem;"><%= pluralize(current_user.shots.count, "Shot")%></span>
                    <%= link_to my_shots_path , style: "text-decoration: none; color : black; font-size : 1.2rem;" do %>
                        (<%if current_user.shots.count > 0%>
                            View
                        <%else%>
                            Create
                        <%end%>
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"/>
                        </svg>)
                    <% end %>
                </div>
            </div>
        </div>
        <div class="right_side_follower_and_following_div">
            <div class="following_div_current_user">
                <div class="heading_of_following_user_div">
                    Following
                </div>
                <div class="display_of_following_user_div">
                    <% if current_user.following.count > 0 %>
                        <% current_user.following.each do |follower| %>
                            <div class="inner_single_follower_following_div">
                                <%= link_to  profile_path(follower.id), style: "text-decoration: none; color: black; font-size: 1.2rem; display: flex; align-items : center;" do %>
                                <%= image_tag(follower.image, height: "40rem", width: "40rem", style: 'border-radius: 50%;') %>
                                You are following to<%=" "%><%= follower.name %>.
                                <%= button_to "Unfollow", unfollow_path(follower), class: "btn btn-outline-primary" ,style: "margin-left : 1rem;" %>
                                <% end %>
                            </div>
                        <%end%>
                    <%else%>
                        <h5 style="text-align : center;">Not Following anyone Yet!</h5>
                    <% end %>
                </div>
            </div>
            <div class="following_div_current_user">
                <div class="heading_of_following_user_div">
                    Followers
                </div>
                <div class="display_of_following_user_div">
                    <% if current_user.followers.count > 0 %>
                        <% current_user.followers.each do |follower| %>
                            <div class="inner_single_follower_following_div">
                                <%= link_to  profile_path(follower.id), style: "text-decoration: none; color: black; font-size: 1.2rem;" do %>
                                <%= image_tag(follower.image, height: "40rem", width: "40rem", style: 'border-radius: 50%;') %>
                                <%= follower.name %> following you.
                                <% end %>
                            </div>
                        <%end%>
                    <%else%>
                        <h5 style="text-align : center;">No Followers Yet!</h5>
                    <%end%>
                </div>
            </div>
        </div>
    </div>
</div> 

app/views/home/follow_request.html.erb
<div class="outer_request_main_div">
    
    <% if current_user.follow_requests.count > 0 %>
        <div class="heading_of_follow_requests">
            Follow Request
        </div>
    <%else%>
        <div class="heading_of_follow_requests">
            No Request Yet!
        </div>
    <% end %>
    

    <% current_user.follow_requests.each do |request|%>
        <div class="inner_request_main_div">
            <div class="inner_request_title_div">
                <div class="inner_request_title_image_div">
                    <%= image_tag(request.followerable.image , height: "50rem" , width: "50rem", style: "border-radius : 50%;")%>
                </div>
                <div class="inner_request_title_text_div">
                    <%= request.followerable.name%> want to follow you
                </div>
            </div>
            <div class="buttons_div_accept_decline_for_request">
                <%= button_to "Accept" , accept_path(request.followerable) , class: "btn btn-success"%>
                <%= button_to "Decline" , decline_path(request.followerable) , class: "btn btn-danger" , style: "margin-left: 1rem;" , onclick: "window.location.reload();"%>
            </div>
        </div>
    <%end%>

</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>